import { z } from "zod";

const str = (max: number) => z.string().trim().max(max).nullable().optional();

export const actualizarConfiguracionSchema = z.object({
  nombreParqueadero: str(100),
  nit: str(30),
  direccion: str(200),
  ciudad: str(100),
  telefono: str(30),
  whatsapp: str(30),
  correo: str(100),
  logo: str(500),
  fondoLogin: str(500),
  colorFondoLogin: str(20),
  colorPrincipal: str(20),
  colorSecundario: str(20),
  colorFondo: str(20),
  modoOscuro: z.boolean().optional(),
  tamanoFuente: str(10),
  formatoFecha: str(20),
  formatoHora: str(10),
  formatoMoneda: str(10),
  zonaHoraria: str(50),
  monedaSimbolo: str(5),
  idioma: str(10),
  notificarWhatsappIngreso: z.boolean().optional(),
  notificarWhatsappSalida: z.boolean().optional(),
  notificarWhatsappReserva: z.boolean().optional(),
  notificarWhatsappVencimiento: z.boolean().optional(),
  notificarEmail: z.boolean().optional(),
  mensajeWhatsappIngreso: str(1000),
  mensajeWhatsappSalida: str(1000),
  mensajeWhatsappFactura: str(1000),
  mensajeWhatsappReserva: str(1000),
  mensajeWhatsappRecordatorio: str(1000),
  mensajeWhatsappVencida: str(1000),
  mensajeWhatsappBienvenida: str(1000),
  horarioApertura: str(10),
  horarioCierre: str(10),
  paginacionPorDefecto: z.number().int().min(1).max(200).optional().nullable(),
  iva: z.number().min(0).max(100).optional().nullable(),
  pieFactura: str(500),
  metodosPago: str(100),
  intentosMaximos: z.number().int().min(1).max(100).optional().nullable(),
  minutosGracia: z.number().int().min(0).max(1440).optional().nullable(),
  listasConfiguracion: z.any().optional().nullable(),
});
