import { z } from "zod";

export const actualizarConfiguracionSchema = z.object({
  nombreParqueadero: z.string().trim().optional().max(100),
  nit: z.string().trim().optional().nullable().max(30),
  direccion: z.string().trim().optional().nullable().max(200),
  ciudad: z.string().trim().optional().nullable().max(100),
  telefono: z.string().trim().optional().nullable().max(30),
  whatsapp: z.string().trim().optional().nullable().max(30),
  correo: z.string().trim().email().optional().nullable().max(100),
  logo: z.string().optional().nullable(),
  fondoLogin: z.string().optional().nullable(),
  colorFondoLogin: z.string().optional().nullable(),
  colorPrincipal: z.string().optional().nullable(),
  colorSecundario: z.string().optional().nullable(),
  colorFondo: z.string().optional().nullable(),
  modoOscuro: z.boolean().optional(),
  tamanoFuente: z.string().trim().optional().nullable().max(10),
  formatoFecha: z.string().trim().optional().nullable().max(20),
  formatoHora: z.string().trim().optional().nullable().max(10),
  formatoMoneda: z.string().trim().optional().nullable().max(10),
  zonaHoraria: z.string().trim().optional().nullable().max(50),
  monedaSimbolo: z.string().trim().optional().nullable().max(5),
  idioma: z.string().trim().optional().nullable().max(10),
  notificarWhatsappIngreso: z.boolean().optional(),
  notificarWhatsappSalida: z.boolean().optional(),
  notificarWhatsappReserva: z.boolean().optional(),
  notificarWhatsappVencimiento: z.boolean().optional(),
  notificarEmail: z.boolean().optional(),
  mensajeWhatsappIngreso: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappSalida: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappFactura: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappReserva: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappRecordatorio: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappVencida: z.string().trim().optional().nullable().max(1000),
  mensajeWhatsappBienvenida: z.string().trim().optional().nullable().max(1000),
  horarioApertura: z.string().trim().optional().nullable().max(10),
  horarioCierre: z.string().trim().optional().nullable().max(10),
  paginacionPorDefecto: z.number().int().min(1).max(200).optional().nullable(),
  iva: z.number().min(0).max(100).optional().nullable(),
  pieFactura: z.string().trim().optional().nullable().max(500),
  metodosPago: z.string().trim().optional().nullable().max(100),
  intentosMaximos: z.number().int().min(1).max(100).optional().nullable(),
  minutosGracia: z.number().int().min(0).max(1440).optional().nullable(),
  listasConfiguracion: z.any().optional().nullable(),
});
