import { z } from "zod";

const str = (max: number) => z.string().trim().max(max);

export const actualizarConfiguracionSchema = z.object({
  nombreParqueadero: str(100).optional(),
  nit: str(30).optional().nullable(),
  direccion: str(200).optional().nullable(),
  ciudad: str(100).optional().nullable(),
  telefono: str(30).optional().nullable(),
  whatsapp: str(30).optional().nullable(),
  correo: z.string().trim().email().max(100).optional().nullable(),
  logo: z.string().optional().nullable(),
  fondoLogin: z.string().optional().nullable(),
  colorFondoLogin: z.string().optional().nullable(),
  colorPrincipal: z.string().optional().nullable(),
  colorSecundario: z.string().optional().nullable(),
  colorFondo: z.string().optional().nullable(),
  modoOscuro: z.boolean().optional(),
  tamanoFuente: str(10).optional().nullable(),
  formatoFecha: str(20).optional().nullable(),
  formatoHora: str(10).optional().nullable(),
  formatoMoneda: str(10).optional().nullable(),
  zonaHoraria: str(50).optional().nullable(),
  monedaSimbolo: str(5).optional().nullable(),
  idioma: str(10).optional().nullable(),
  notificarWhatsappIngreso: z.boolean().optional(),
  notificarWhatsappSalida: z.boolean().optional(),
  notificarWhatsappReserva: z.boolean().optional(),
  notificarWhatsappVencimiento: z.boolean().optional(),
  notificarEmail: z.boolean().optional(),
  mensajeWhatsappIngreso: str(1000).optional().nullable(),
  mensajeWhatsappSalida: str(1000).optional().nullable(),
  mensajeWhatsappFactura: str(1000).optional().nullable(),
  mensajeWhatsappReserva: str(1000).optional().nullable(),
  mensajeWhatsappRecordatorio: str(1000).optional().nullable(),
  mensajeWhatsappVencida: str(1000).optional().nullable(),
  mensajeWhatsappBienvenida: str(1000).optional().nullable(),
  horarioApertura: str(10).optional().nullable(),
  horarioCierre: str(10).optional().nullable(),
  paginacionPorDefecto: z.number().int().min(1).max(200).optional().nullable(),
  iva: z.number().min(0).max(100).optional().nullable(),
  pieFactura: str(500).optional().nullable(),
  metodosPago: str(100).optional().nullable(),
  intentosMaximos: z.number().int().min(1).max(100).optional().nullable(),
  minutosGracia: z.number().int().min(0).max(1440).optional().nullable(),
  listasConfiguracion: z.any().optional().nullable(),
});
